version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  redis:
    image: redis:latest
    platform: linux/amd64
    command: redis-server
    volumes:
      - redis:/var/lib/redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpasswordhere
      MYSQL_DATABASE: CloudStorageDB
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
  redis:
  minio_data:
networks:
  redis-network:
    driver: bridge